name: lec-trafficking-gnn
channels:
  - conda-forge
  - pytorch
  - pyg
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - scanpy
  - anndata
  - openpyxl
  - xlrd
  - requests
  - pyyaml
  - matplotlib
  - seaborn
  - jupyterlab
  - python-igraph
  - leidenalg
  - networkx
  - python-louvain
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - torch-geometric
      - scvi-tools
      - GEOparse
      - gseapy
      - harmonypy
      - arboreto
      - pytest
      - mypy
      - types-PyYAML
      - types-requests
